"""initial schema

Revision ID: f14291cf0bec
Revises: 
Create Date: 2026-06-08 12:11:05.364230
"""
from alembic import op
import sqlalchemy as sa


revision = 'f14291cf0bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_codes_id'), ['id'], unique=False)

    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_key', ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limits_key'), ['key'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=True),
    sa.Column('scan_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('progress_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_job_id'), ['job_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_scan_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('pqc_score', sa.Float(), nullable=True),
    sa.Column('pqc_status', sa.String(length=32), nullable=True),
    sa.Column('tls_version', sa.String(length=16), nullable=True),
    sa.Column('cipher_suite', sa.String(length=128), nullable=True),
    sa.Column('scan_status', sa.String(length=32), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_target'), ['target'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_history_target'))
        batch_op.drop_index(batch_op.f('ix_scan_history_id'))

    op.drop_table('scan_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_id'))

    op.drop_table('scan_jobs')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_id'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limits_key'))
        batch_op.drop_index(batch_op.f('ix_rate_limits_id'))
        batch_op.drop_index('ix_rate_limit_key')

    op.drop_table('rate_limits')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_id'))
        batch_op.drop_index(batch_op.f('ix_otp_codes_email'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
